      PROGRAM STATISTICSPROGRAM
      IMPLICIT NONE
      INTEGER DATAARRAY(5)
      INTEGER SMALLESTVALUE, LARGESTVALUE, MODEVALUE
      INTEGER I
      CALL READDATA(DATAARRAY)
      CALL FINDSMALLEST(DATAARRAY, SMALLESTVALUE)
      CALL FINDLARGEST(DATAARRAY, LARGESTVALUE)
      CALL FINDMODE(DATAARRAY, MODEVALUE)
      PRINT *, 'SMALLEST VALUE:', SMALLESTVALUE
      PRINT *, 'LARGEST VALUE:', LARGESTVALUE
      PRINT *, 'MODE VALUE:', MODEVALUE
      STOP
      END

      SUBROUTINE READDATA(ARR)
      INTEGER ARR(5)
      INTEGER I
      PRINT *, 'ENTER 5 INTEGER VALUES:'
      DO 10 I = 1, 5
         READ(*, *) ARR(I)
   10 CONTINUE
      RETURN
      END

      SUBROUTINE FINDSMALLEST(ARR, SMALLEST)
      INTEGER ARR(5)
      INTEGER SMALLEST
      INTEGER I
      SMALLEST = ARR(1)
      DO 20 I = 2, 5
         IF (ARR(I) .LT. SMALLEST) THEN
            SMALLEST = ARR(I)
         END IF
   20 CONTINUE
      RETURN
      END

      SUBROUTINE FINDLARGEST(ARR, LARGEST)
      INTEGER ARR(5)
      INTEGER LARGEST
      INTEGER I
      LARGEST = ARR(1)
      DO 30 I = 2, 5
         IF (ARR(I) .GT. LARGEST) THEN
            LARGEST = ARR(I)
         END IF
   30 CONTINUE
      RETURN
      END

      SUBROUTINE FINDMODE(ARR, MODE)
      INTEGER ARR(5)
      INTEGER MODE
      INTEGER I, J, MODECOUNT, CURRENTCOUNT
      MODECOUNT = 0
      DO 40 I = 1, 5
         CURRENTCOUNT = 0
         DO 50 J = 1, 5
            IF (ARR(I) .EQ. ARR(J)) THEN
               CURRENTCOUNT = CURRENTCOUNT + 1
            END IF
   50    CONTINUE
         IF (CURRENTCOUNT .GT. MODECOUNT) THEN
            MODECOUNT = CURRENTCOUNT
            MODE = ARR(I)
         END IF
   40 CONTINUE
      RETURN
      END